---

# configure docker

- name: add docker apt repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker packer to sources
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker-ce and docker-compose
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-compose

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    group: docker
    append: yes

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    group: docker
    append: yes
